### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [gisler/RPhosFate#17]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by rsbivand** [comment]
[00check.log](https://github.com/gisler/RPhosFate/files/11141271/00check.log)
[00install.out.txt](https://github.com/gisler/RPhosFate/files/11141272/00install.out.txt)
is a recent check log from running under `_SP_EVOLUTION_STATUS_=2` without retiring r-spatial packages (suggested in this package) on the library path. The minimal correction is to check that the package namespaces can be loaded, and if not, do not run those parts of the examples. It would be safer in the longer term to replace retiring r-spatial packages with active r-spatial/rspatial packages (see https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). This should resolve when https://github.com/hzambran/hydroTSM/issues/19 is dealt with.

**Comment by gisler** [comment]
Thank you for pointing this out. I suppose it will be fixed within `hydroTSM` in the near future. And if not, I guess I can simply drop the `hydroGOF` dependency and implement the handful of required functions myself.

Depending on what the future brings, I might also switch from `raster` to `terra`.

**Comment by rsbivand** [comment]
@gisler  https://github.com/hzambran/hydroTSM/issues/19 has not moved, so please contact the maintainer to see whether you need to step around that omission now. See also https://r-spatial.org/r/2023/04/10/evolution3.html and https://r-spatial.org/r/2023/05/15/evolution4.html.

**Comment by gisler** [comment]
@rsbivand Hi Roger! Sorry for answering late, but summer is always a difficult time. I contacted Mauricio now. Lets see what happens.

**Comment by gisler** [comment]
@rsbivand Hi! I just got news that he is working on a new version without the retiring dependencies and is going to submit it after the CRAN holidays. 😀

**Comment by rsbivand** [comment]
@gisler Thanks, I checked https://github.com/hzambran/hydroTSM/issues/19#issuecomment-1666454191 and suggested a fix for a warning that may show up on CRAN checks.

**Comment by rsbivand** [comment]
@gisler I'm afraid https://github.com/hzambran/hydroTSM/issues/19 is still in progress, so maybe get in touch and be ready to move hydroGOF to Suggests and condition on its availability. Less than three weeks remain to fix this.

**Comment by gisler** [comment]
@rsbivand Thanks for reminding me. Time is running way too fast. But I guess I'll prepare to remove `hydroGOF` completely. It shouldn't be that much work.
